--
-- PostgreSQL database dump
--

-- Dumped from database version 16.5
-- Dumped by pg_dump version 16.5

-- Started on 2024-11-20 22:45:03

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 16825)
-- Name: fan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fan (
    fan_id bigint NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    first_occupation character varying(255),
    preferred_stand character varying(255),
    reservation_time character varying(255)
);


ALTER TABLE public.fan OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16824)
-- Name: fan_fan_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.fan_fan_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.fan_fan_id_seq OWNER TO postgres;

--
-- TOC entry 4853 (class 0 OID 0)
-- Dependencies: 215
-- Name: fan_fan_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.fan_fan_id_seq OWNED BY public.fan.fan_id;


--
-- TOC entry 218 (class 1259 OID 16864)
-- Name: reward; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reward (
    id bigint NOT NULL,
    fan_id bigint NOT NULL,
    seat_id character varying(255) NOT NULL
);


ALTER TABLE public.reward OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16863)
-- Name: reward_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reward ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reward_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4693 (class 2604 OID 16869)
-- Name: fan fan_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fan ALTER COLUMN fan_id SET DEFAULT nextval('public.fan_fan_id_seq'::regclass);


--
-- TOC entry 4845 (class 0 OID 16825)
-- Dependencies: 216
-- Data for Name: fan; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.fan (fan_id, first_name, last_name, email, phone, first_occupation, preferred_stand, reservation_time) FROM stdin;
317	Albert	Wesker	a.wesker@umbrealla.corp	417-666-1000	OTH	NORTH	2024-05-01T14:30:00
318	Ada	Wong	a.wong@tricell.inc	417-555-2000	MLT	SOUTH	2024-05-01T16:00:00
319	Barry	Burton	b.burton@rpd.mo.gov	417-333-3000	MLT	EAST	2024-05-02T10:00:00
320	Chris	Redfield	c.redfield@bsaa.gov	417-222-4000	MLT	WEST	2024-05-02T12:30:00
321	Claire	Redfield	c.redfield@terrasave.org	417-111-5000	STU	NORTH	2024-05-03T14:00:00
322	Jill	Valentine	j.valentine@bsaa.gov	417-777-6000	MLT	SOUTH	2024-05-03T16:30:00
323	Leon	Kennedy	l.kennedy@dso.gov	417-888-7000	MLT	EAST	2024-05-04T10:30:00
324	Rebecca	Chambers	r.chambers@terrasave.org	417-999-8000	EDU	WEST	2024-05-04T12:00:00
325	Sheva	Alomar	s.alomar@bsaa.gov	417-000-9000	MLT	NORTH	2024-05-05T14:30:00
326	Ethan	Winters	e.winters@blueumbrella.corp	417-123-0000	OTH	SOUTH	2024-05-05T16:00:00
327	Mia	Winters	m.winters@theconnections.org	417-234-1000	OTH	EAST	2024-05-06T10:00:00
328	Rose	Winters	r.winters@bsaa.gov	417-345-2000	STU	WEST	2024-05-06T12:30:00
329	Jake	Muller	j.muller@dso.org	417-456-3000	MLT	NORTH	2024-05-07T14:00:00
330	Sherry	Birkin	s.birkin@dso.org	417-567-4000	MLT	SOUTH	2024-05-07T16:30:00
331	Carlos	Oliveira	c.oliveira@umbrella.corp	417-678-5000	MLT	EAST	2024-05-08T10:30:00
332	Billy	Coen	b.coen@aol.com	417-789-6000	OTH	WEST	2024-05-08T12:00:00
333	Steve	Burnside	s.burnside@drgonfly.corp	417-890-7000	OTH	NORTH	2024-05-09T14:30:00
334	Luis	Sera	l.sera@umbrella.corp	417-901-8000	EDU	SOUTH	2024-05-09T16:00:00
335	Ashley	Graham	a.graham@us.gov	417-012-9000	STU	EAST	2024-05-10T10:00:00
336	Helena	Harper	h.harper@usss.us.gov	417-123-0001	MLT	WEST	2024-05-10T12:30:00
337	Piers	Nivans	p.nivans@bsaa.gov	417-234-1001	MLT	NORTH	2024-05-11T14:00:00
338	Josh	Stone	j.stone@stars.rpd.mo.gov	417-345-2001	MLT	SOUTH	2024-05-11T16:30:00
339	HUNK	Unknown	hunk@umbrella.corp	417-456-3001	MLT	EAST	2024-05-12T10:30:00
340	William	Birkin	w.birkin@umbrella.corp	417-567-4001	EDU	WEST	2024-05-12T12:00:00
341	Annette	Birkin	a.birkin@umbrella.corp	417-678-5001	EDU	NORTH	2024-05-13T14:30:00
342	Alfred	Ashford	alfred.ashford@umbrella.corp	417-789-6001	OTH	SOUTH	2024-05-13T16:00:00
343	Alexia	Ashford	alexia.ashford@umbrella.corp	417-890-7001	EDU	EAST	2024-05-14T10:00:00
344	Ozwell	E. Spencer	o.spencer@umbrella.corp	417-901-8001	OTH	WEST	2024-05-14T12:30:00
345	James	Marcus	j.marcus@umbrella.corp	417-012-9001	EDU	NORTH	2024-05-15T14:00:00
346	Edward	Dewey	e.dewey@stars.rpd.mo.gov	417-123-0002	MLT	SOUTH	2024-05-15T16:30:00
347	Forest	Speyer	f.speyer@stars.rpd.mo.gov	417-234-1002	MLT	EAST	2024-05-16T10:30:00
348	Kenneth	Sullivan	k.sullivan@stars.rpd.mo.gov	417-345-2002	MLT	WEST	2024-05-16T12:00:00
349	Richard	Aiken	r.aiken@stars.rpd.mo.gov	417-456-3002	MLT	NORTH	2024-05-17T14:30:00
\.


--
-- TOC entry 4847 (class 0 OID 16864)
-- Dependencies: 218
-- Data for Name: reward; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reward (id, fan_id, seat_id) FROM stdin;
973	349	N601
974	345	N602
975	329	N603
976	337	N604
977	325	N605
978	320	W501
979	324	W502
980	328	W503
981	318	S101
982	330	S102
983	326	S103
984	338	S104
985	322	S105
986	319	E001
987	323	E002
988	327	E003
\.


--
-- TOC entry 4854 (class 0 OID 0)
-- Dependencies: 215
-- Name: fan_fan_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fan_fan_id_seq', 349, true);


--
-- TOC entry 4855 (class 0 OID 0)
-- Dependencies: 217
-- Name: reward_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reward_id_seq', 988, true);


--
-- TOC entry 4695 (class 2606 OID 16834)
-- Name: fan fan_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fan
    ADD CONSTRAINT fan_email_key UNIQUE (email);


--
-- TOC entry 4697 (class 2606 OID 16871)
-- Name: fan fan_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fan
    ADD CONSTRAINT fan_pkey PRIMARY KEY (fan_id);


--
-- TOC entry 4699 (class 2606 OID 16868)
-- Name: reward reward_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reward
    ADD CONSTRAINT reward_pkey PRIMARY KEY (id);


--
-- TOC entry 4700 (class 2606 OID 16879)
-- Name: reward fkii6k8alujsai0n3t3t359brp8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reward
    ADD CONSTRAINT fkii6k8alujsai0n3t3t359brp8 FOREIGN KEY (fan_id) REFERENCES public.fan(fan_id);


-- Completed on 2024-11-20 22:45:03

--
-- PostgreSQL database dump complete
--

